jobType: contract
analysisName: shawn analysis
analysisDesc: sample analysis
lastSuccessfulRunId: 6019997faf4091399cea7dc2
lastRunId: 6018887faf4091399cea7de7
createdBy: Shawn
createdDate: '2020-02-03'
lastModifiedDate: '2020-02-03'
status: unpublished
associatedStructureFile: 25c915c3-f87a-465c-a4ed-969110345ba0
associatedEventLosses:
